version: '2.3'

services:

  mysql:
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: conductor
      MYSQL_USER: conductor
      MYSQL_PASSWORD: password
    volumes:
      - ./opt/mysql:/var/lib/mysql:rw
    networks:
      - internal
    ports:
      - 3306:3306
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/3306'
      interval: 5s
      timeout: 5s
      retries: 12

volumes:
  conductor_mysql:

networks:
  internal:
    driver: bridge
    ipam:
     config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
