version: '2.3'

services:

  postgres:
    image: postgres
    restart: always
    networks:
      - internal
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=conductor
      - POSTGRES_USER=conductor
      - POSTGRES_PASSWORD=example
    volumes:
      - ./opt/postgres:/var/lib/postgresql/data:rw

networks:
  internal:
    driver: bridge
    ipam:
     config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
