version: '3'

services:
  conductor-server:
    environment:
      - CONFIG_PROP=${CONDUCTOR_CONFIG_FILE:-config-minimal.properties}
    image: conductor:server
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    networks:
      - internal
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"

networks:
  internal: